# Generated by Django 4.1 on 2022-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("App", "Application"),
                            ("Scripts", "Scripts"),
                            ("Web", "Website"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("start", models.CharField(max_length=50)),
                ("end", models.CharField(max_length=50)),
                ("structure", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "resume_type",
                    models.CharField(
                        choices=[
                            ("Community", "Community"),
                            ("Professional", "Professional"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
