# Generated by Django 4.1 on 2024-03-25 00:17

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import website.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=website.utils.generate_uuid, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.basemodel')),
                ('image', models.ImageField(upload_to='profiles/')),
                ('content', django_quill.fields.QuillField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('website.basemodel',),
        ),
    ]
