# Generated by Django 4.1 on 2024-03-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'Biographies'},
        ),
    ]
