# Generated by Django 4.1 on 2023-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='email',
            field=models.EmailField(default='edghimakoll@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='phone',
            field=models.CharField(default='+237 6 91 67 83 78', max_length=13),
        ),
    ]
