# Generated by Django 4.1 on 2024-03-31 22:46

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import website.constants


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_biography_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_image', models.ImageField(null=True, upload_to='companies/')),
                ('company_link', models.URLField(blank=True, null=True)),
                ('company_location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-time', 'FULL_TIME'), ('Part-time', 'PART_TIME'), ('Self-employed', 'SELF_EMPLOYED'), ('Freelance', 'FREELANCE'), ('Contract', 'CONTRACT'), ('Internship', 'INTERNSHIP'), ('Apprenticeship', 'APPRENTICESHIP'), ('Seasonal', 'SEASONAL')], default=website.constants.EmploymentType['FREELANCE'], max_length=20)),
                ('employment_location', models.CharField(choices=[('On-site', 'ON_SITE'), ('Remote', 'REMOTE'), ('Hybrid', 'HYBRID')], default=website.constants.EmploymentLocation['REMOTE'], max_length=20)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('work_description', django_quill.fields.QuillField()),
                ('position', models.IntegerField(unique=True)),
                ('display', models.BooleanField(default=True)),
            ],
            bases=('website.basemodel',),
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.basemodel')),
                ('file', models.FileField(upload_to='resumes/')),
                ('version', models.IntegerField(unique=True)),
            ],
            bases=('website.basemodel',),
        ),
    ]
