# Generated by Django 4.1 on 2023-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_count_hide_alter_aboutinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
