# Generated by Django 4.1 on 2024-03-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_resume_resumefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='company_image',
            field=models.ImageField(default=None, null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='company_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
