# Generated by Django 4.1 on 2024-03-31 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_resume_company_image_alter_resume_company_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='work_description',
            new_name='description',
        ),
    ]
